# -*- coding: utf-8 -*-
"""Proyecto final de machine learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1135wsyyCRI0FBw1z9IozCzTGLX8-sAKX

# **Trabajo Final Machine Learning**
## **William Sebastian Cabrera Buitrago , Samuel David Rojas Cárdenas**

# <FONT SIZE=5 COLOR="DarkTurquoise"> **Librerias** </FONT>
"""

# librerías para procesar
import numpy  as np
import pandas as pd

# librerías para graficar
import matplotlib.pyplot as plt
import seaborn           as sns
import plotly.express    as px
import missingno         as msno

# Algunos elementos de preprocesamiento: escalamiento y selección de k en k-means
from sklearn.preprocessing      import StandardScaler, MinMaxScaler
from sklearn.preprocessing      import LabelEncoder, OneHotEncoder
from sklearn.compose            import ColumnTransformer
from sklearn.pipeline           import Pipeline as ImbPipeline
from sklearn.metrics            import silhouette_samples, silhouette_score

#Algoritmos de CLasificación
from sklearn.linear_model       import LogisticRegression
from sklearn.tree               import DecisionTreeClassifier
from sklearn.ensemble           import RandomForestClassifier

# Para el algoritmo k-means
from sklearn.cluster           import KMeans

# Para otros algoritmos de machine learning
from sklearn.decomposition     import PCA
from sklearn.neighbors         import KNeighborsClassifier
from sklearn.neighbors         import NearestNeighbors
from sklearn.metrics           import pairwise_distances_argmin_min
from sklearn.preprocessing import StandardScaler

#Para omitir los warnings
import warnings
warnings.filterwarnings("ignore")
import missingno as msno
# Métricas
from sklearn                     import metrics
from sklearn.metrics             import mean_squared_error, r2_score

# Para gráficos y data.frames
import pandas as pd
import numpy  as np

# librerías para graficar
import plotly.express     as px
import matplotlib.pyplot  as plt
import seaborn            as sns


# Dividir los datos entrenamiento y prueba
from sklearn.model_selection     import train_test_split
from sklearn.feature_selection   import RFE

# Para preprocesamiento: escalador
from sklearn.preprocessing       import StandardScaler

# Modelo de regresión
from sklearn.linear_model        import LinearRegression
from sklearn.svm                 import SVR
from sklearn.neighbors           import KNeighborsRegressor
from sklearn.tree                import DecisionTreeRegressor
from sklearn.ensemble            import RandomForestRegressor

# Métricas
from sklearn                     import metrics
from sklearn.metrics             import confusion_matrix, ConfusionMatrixDisplay, classification_report
from sklearn.metrics             import accuracy_score, precision_score, recall_score, f1_score
from imblearn.metrics            import specificity_score
from sklearn.metrics             import mean_squared_error, mean_absolute_error, r2_score

import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import ipywidgets as widgets
from ipywidgets import interact
from sklearn.model_selection import train_test_split

from sklearn.metrics            import confusion_matrix, ConfusionMatrixDisplay, classification_report
from sklearn.metrics            import accuracy_score, precision_score, recall_score, f1_score
from imblearn.metrics           import specificity_score
from sklearn.metrics            import mean_squared_error, mean_absolute_error, r2_score

def evaluacion_modelo(modelo, X_train, y_train, X_test, y_test, nombre_modelo = "modelo",graficar = True):
  # definir las predicciones en conjuntos de train y test
  y_pred_train = modelo.predict(X_train)
  y_pred_test  = modelo.predict(X_test)
  # matrices de confusión
  if graficar :
    # Calcular matrices de confusión
    cm_train = confusion_matrix(y_train, y_pred_train)
    cm_test = confusion_matrix(y_test, y_pred_test)
    # ejes para gráficas
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    # matriz de confusión en train
    sns.heatmap(pd.DataFrame(cm_train),                # data.frame
                  annot=True,                          # colocar números de las cajitas
                  annot_kws = {'size':20},             # tamaño de la letra
                  cmap="YlOrRd",                       # color de la letra 'Pastel1', 'Pastel1_r', 'Pastel2', 'Pastel2_r', 'PiYG', 'PiYG_r', 'PuBu'
                  fmt='g',                             # para que salgan los número no : notación científica
                  ax=axes[0])
    axes[0].set_title(f'Matriz de Confusión - Train-{nombre_modelo}', fontsize=14)
    axes[0].set_xlabel('Predicciones')
    axes[0].set_ylabel('Valores Reales')
    # matriz de confusión en test
    sns.heatmap(pd.DataFrame(cm_test),
              annot=True,
              fmt='g',
              cmap='YlOrRd',
              annot_kws={'size':16},
              ax=axes[1])
    axes[1].set_title(f'Matriz de Confusión - Test-{nombre_modelo}', fontsize=14)
    axes[1].set_xlabel('Predicciones')
    axes[1].set_ylabel('Valores Reales')
    plt.tight_layout()
    plt.show()
  # metricas en train
  metrics=["accuracy", "recall" , "specificity", "precision", "f1"]
  # valores
  values_train = [accuracy_score(y_train,y_pred_train),
          recall_score(y_train,y_pred_train),
          specificity_score(y_train,y_pred_train),
          precision_score(y_train,y_pred_train),
          f1_score(y_train,y_pred_train)]
  values_test = [accuracy_score(y_test,y_pred_test),
          recall_score(y_test,y_pred_test),
          specificity_score(y_test,y_pred_test),
          precision_score(y_test,y_pred_test),
          f1_score(y_test,y_pred_test)]

  df = pd.DataFrame({f"{nombre_modelo}_train" : values_train,
                      f"{nombre_modelo}_test" : values_test}, index = metrics)
  return df

def evaluacion_regresion(modelo, X_train, y_train, X_test, y_test, nombre_modelo="modelo", graficar=True):
    # Predicciones
    y_pred_train = modelo.predict(X_train)
    y_pred_test  = modelo.predict(X_test)

    if graficar:
        plt.figure(figsize=(6,6))
        plt.scatter(y_test, y_pred_test, alpha=0.5)
        plt.plot([y_test.min(), y_test.max()],
                 [y_test.min(), y_test.max()],
                 linestyle='--')
        plt.xlabel("Valores reales")
        plt.ylabel("Predicciones")
        plt.title(f"Predicción vs Real - {nombre_modelo}")
        plt.show()

    metrics = ["R2", "MSE", "RMSE", "MAE"]

    values_train = [
        r2_score(y_train, y_pred_train),
        mean_squared_error(y_train, y_pred_train),
        np.sqrt(mean_squared_error(y_train, y_pred_train)),
        mean_absolute_error(y_train, y_pred_train)
    ]

    values_test = [
        r2_score(y_test, y_pred_test),
        mean_squared_error(y_test, y_pred_test),
        np.sqrt(mean_squared_error(y_test, y_pred_test)),
        mean_absolute_error(y_test, y_pred_test)
    ]

    df = pd.DataFrame({
        f"{nombre_modelo}_train": values_train,
        f"{nombre_modelo}_test": values_test
    }, index=metrics)

    return df

"""# <FONT SIZE=5 COLOR="DarkTurquoise"> **1. Clasificación** </FONT>"""

data = pd.read_csv("/content/x.csv" , sep=';', encoding='utf-8', decimal=',')
url = "https://archive.ics.uci.edu/dataset/848/secondary+mushroom+dataset"
data.head()

"""##**analisis exploratorio de datos**"""

def histograma(datos, variable, analisis=""):
    plt.figure(figsize=(8,5))
    vals = datos[variable].dropna()
    plt.hist(vals, bins=15)
    plt.title(f"Histograma de {variable}")
    if analisis:
        plt.gca().text(0.01, 0.95, analisis, transform=plt.gca().transAxes,
                       fontsize=10, verticalalignment='top')
    plt.xlabel(variable)
    plt.ylabel("Frecuencia")
    plt.show()

def boxplot(datos, variable, analisis=""):
    plt.figure(figsize=(6,5))
    vals = datos[variable].dropna()
    plt.boxplot(vals, vert=True)
    plt.title(f"Boxplot de {variable}")
    if analisis:
        plt.gca().text(0.01, 0.95, analisis, transform=plt.gca().transAxes,
                       fontsize=10, verticalalignment='top')
    plt.ylabel(variable)
    plt.show()

def detect_outliers_iqr(datos, variable):
    col = datos[variable].dropna()
    Q1 = np.percentile(col, 25)
    Q3 = np.percentile(col, 75)
    IQR = Q3 - Q1
    lim_sup = Q3 + 1.5 * IQR
    lim_inf = Q1 - 1.5 * IQR
    mask = (datos[variable] < lim_inf) | (datos[variable] > lim_sup)
    # devolver máscara alineada al índice original (NaN -> False)
    return mask.reindex(datos.index, fill_value=False), lim_inf, lim_sup

data.info()

data.describe()

data.isnull().sum()

data2 = data.drop(columns=['cap-surface', 'gill-attachment', "gill-spacing",'stem-root','stem-surface','veil-type','veil-color','ring-type','spore-print-color'])

numeric_cols = ['cap-diameter','stem-height','stem-width']
categorical_cols = ['cap-shape','cap-color','does-bruise-or-bleed','gill-color',
 'stem-color','has-ring','habitat','season']

variable_objetivo = data2["class"]

for col in numeric_cols:
    if col not in data2.columns:
        print(f"[!] Columna numérica {col} no encontrada. Se omite.")
        continue
    data2[col] = pd.to_numeric(data2[col], errors='coerce')
    histograma(data2, col)
    print("\n")
    boxplot(data2, col)
    print("\n")

for col in categorical_cols:
    if col not in data2.columns:
        print(f"[!] Columna categórica {col} no encontrada. Se omite.")
        continue
    counts = data2[col].value_counts(dropna=False)
    # gráfico de barras
    plt.figure(figsize=(8,4))
    counts_sorted = counts.sort_values(ascending=False)
    plt.bar(counts_sorted.index.astype(str), counts_sorted.values)
    plt.title(f"Distribución de {col}")
    plt.xlabel(col)
    plt.ylabel("Cuenta")
    plt.xticks(rotation=45, ha='right')
    plt.tight_layout()
    plt.show()

"""El análisis de las variables numéricas revela distribuciones asimétricas con presencia de valores atípicos significativos, particularmente en el diámetro del sombrero (cap-diameter) y el ancho del tallo (stem-width), donde se observan mediciones extremas que podrían corresponder a especies atípicas o errores de medición. La altura del tallo (stem-height) muestra una distribución más concentrada, aunque igualmente con valores extremos que requieren consideración en el preprocesamiento de datos.

En cuanto a las variables categóricas, se identifica un marcado desbalance en características como la presencia de anillo (has-ring) y el hábitat, donde ciertas categorías predominan ampliamente sobre otras. La forma y color del sombrero presentan distribuciones más diversificadas, mientras que la característica de magulladura o sangrado (does-bruise-or-bleed) muestra una distribución relativamente equilibrada que podría ser informativa para la clasificación.

Estos patrones de distribución justifican la aplicación de técnicas de escalado para las variables numéricas y el uso de estrategias como ponderación de clases o muestreo para abordar los desbalances categóricos, optimizando así el rendimiento predictivo de los modelos en este dataset de características morfológicas de hongos.

##**Modelo Clasificación**
"""

X = data2[numeric_cols + categorical_cols].copy()

y = variable_objetivo

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state= 42, stratify=y)

preprocessor = ColumnTransformer([
    ('num', StandardScaler(), numeric_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
], remainder='drop')

"""###**Regresion Logistica**"""

from sklearn.pipeline import Pipeline

Log_reg_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                                   ('classifier', LogisticRegression(random_state=0, max_iter=1000))])

Log_reg_pipeline.fit(X_train, y_train)

y_pred_log = Log_reg_pipeline.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, f1_score, classification_report
from imblearn.metrics import specificity_score

print("Matriz de Confusión Regresion Logistica \n\n", confusion_matrix(y_test, y_pred_log), "\n")

metrics=["accuracy", "recall" , "precision", "f1"]
values = [accuracy_score(y_test,y_pred_log),
          recall_score(y_test,y_pred_log, average='weighted'),
          precision_score(y_test,y_pred_log, average='weighted'),
          f1_score(y_test,y_pred_log, average='weighted')]
print("Métricas \n", pd.DataFrame({"metrics": metrics , "values" : values}), "\n")

print("Resumen evaluación \n", classification_report(y_test, y_pred_log))

cm = confusion_matrix(y_test, y_pred_log)


sns.heatmap(cm,
            annot=True,
            annot_kws = {'size':20},
            cmap='Reds',
            fmt="g")
plt.title('Matriz de Confusión')
plt.xlabel('Predicción')
plt.ylabel('Real')
plt.show()

"""###**Random Forest**"""

from sklearn.pipeline import Pipeline

Rand_for_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                                   ('classifier', RandomForestClassifier(random_state=0))])

Rand_for_pipeline.fit(X_train, y_train)

y_pred_Rand = Rand_for_pipeline.predict(X_test)

print("Matriz de Confusión Random Forest\n\n", confusion_matrix(y_test, y_pred_Rand), "\n")

metrics=["accuracy", "recall" , "precision", "f1"]
values = [accuracy_score(y_test,y_pred_Rand),
          recall_score(y_test,y_pred_Rand, average='weighted'),
          precision_score(y_test,y_pred_Rand, average='weighted'),
          f1_score(y_test,y_pred_Rand, average='weighted')]
print("Métricas \n", pd.DataFrame({"metrics": metrics , "values" : values}), "\n")

print("Resumen evaluación \n", classification_report(y_test, y_pred_Rand))

cm = confusion_matrix(y_test, y_pred_Rand)


sns.heatmap(cm,
            annot=True,
            annot_kws = {'size':20},
            cmap='Reds',
            fmt="g")
plt.title('Matriz de Confusión')
plt.xlabel('Predicción')
plt.ylabel('Real')
plt.show()

"""###**Arboles de Decision**"""

from sklearn.pipeline import Pipeline

dtree_for_pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                                   ('classifier', DecisionTreeClassifier(random_state = 123))])

dtree_for_pipeline.fit(X_train, y_train)

y_pred_dtree = dtree_for_pipeline.predict(X_test)

print("Matriz de Confusión Arboles de Desición\n\n", confusion_matrix(y_test, y_pred_dtree), "\n")

metrics=["accuracy", "recall" , "precision", "f1"]
values = [accuracy_score(y_test,y_pred_dtree),
          recall_score(y_test,y_pred_dtree, average='weighted'),
          precision_score(y_test,y_pred_dtree, average='weighted'),
          f1_score(y_test,y_pred_dtree, average='weighted')]
print("Métricas \n", pd.DataFrame({"metrics": metrics , "values" : values}), "\n")

print("Resumen evaluación \n", classification_report(y_test, y_pred_dtree))

cm = confusion_matrix(y_test, y_pred_dtree)


sns.heatmap(cm,
            annot=True,
            annot_kws = {'size':20},
            cmap='Reds',
            fmt="g")
plt.title('Matriz de Confusión')
plt.xlabel('Predicción')
plt.ylabel('Real')
plt.show()

"""###**Curvas ROC**"""

from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(y_train)
y_test_encoded = le.transform(y_test)

models = {
    'LogisticRegression': Log_reg_pipeline,
    'DecisionTree': dtree_for_pipeline,
    'RandomForest': Rand_for_pipeline
}

plt.figure(figsize=(8,6))
for name, pipeline in models.items():
    pipeline.fit(X_train, y_train)
    y_score = pipeline.predict_proba(X_test)[:,1]
    fpr, tpr, _ = roc_curve(y_test_encoded, y_score)
    auc = roc_auc_score(y_test_encoded, y_score)
    plt.plot(fpr, tpr, label=f"{name} (AUC={auc:.3f})")

plt.plot([0,1],[0,1], linestyle='--', color='gray')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC")
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

"""###**Predicciones**"""

nuevos_datos = pd.DataFrame({
    'cap-diameter': [3.5, 8.0, 5.2],
    'stem-height': [4.2, 9.1, 6.8],
    'stem-width': [0.8, 1.5, 1.2],
    'cap-shape': ['convex', 'flat', 'conical'],
    'cap-color': ['brown', 'white', 'yellow'],
    'does-bruise-or-bleed': ['no', 'yes', 'no'],
    'gill-color': ['white', 'pink', 'black'],
    'stem-color': ['white', 'brown', 'white'],
    'has-ring': ['yes', 'no', 'yes'],
    'habitat': ['grasses', 'woods', 'paths'],
    'season': ['autumn', 'summer', 'spring']
})

# Verificar que las columnas coincidan
print("Columnas de nuevos datos:", nuevos_datos.columns.tolist())
print("Columnas esperadas:", X.columns.tolist())

# Realizar predicciones con ambos modelos
predicciones_rf = Rand_for_pipeline.predict(nuevos_datos)
predicciones_dt = dtree_for_pipeline.predict(nuevos_datos)
predicciones_lg = Log_reg_pipeline.predict(nuevos_datos)

print("\n" + "="*50)
print(" Presicciones con datos más Fáciles")
print("="*50)
print("\nRandom Forest:")
print(predicciones_rf)
print("\nDecision Tree:")
print(predicciones_dt)
print("\nRegresion Logistica:")
print(predicciones_lg)

# Probabilidades de predicción
probabilidades_rf = Rand_for_pipeline.predict_proba(nuevos_datos)
probabilidades_dt = dtree_for_pipeline.predict_proba(nuevos_datos)
probabilidades_lg = Log_reg_pipeline.predict_proba(nuevos_datos)

print("\nProbabilidades - Random Forest:")
print(probabilidades_rf)
print("\nProbabilidades - Decision Tree:")
print(probabilidades_dt)
print("\nProbabilidades - Regresion Logistica:")
print(probabilidades_lg)

#mejor modelo, con datos mas dificles
nuevos_datos_dificiles = pd.DataFrame({
    'cap-diameter': [2.0, 15.5, 7.8, 4.2, 12.0, 1.5, 9.3],
    'stem-height': [3.1, 12.8, 5.5, 6.2, 8.9, 2.8, 7.4],
    'stem-width': [0.5, 2.3, 1.1, 0.9, 1.8, 0.3, 1.4],
    'cap-shape': ['convex', 'flat', 'conical', 'bell', 'sunken', 'convex', 'flat'],
    'cap-color': ['white', 'green', 'yellow', 'brown', 'red', 'white', 'purple'],
    'does-bruise-or-bleed': ['no', 'yes', 'no', 'yes', 'yes', 'no', 'yes'],
    'gill-color': ['white', 'black', 'pink', 'brown', 'green', 'white', 'orange'],
    'stem-color': ['white', 'brown', 'white', 'yellow', 'red', 'white', 'blue'],
    'has-ring': ['yes', 'no', 'yes', 'no', 'yes', 'yes', 'no'],
    'habitat': ['grasses', 'woods', 'paths', 'leaves', 'urban', 'grasses', 'woods'],
    'season': ['spring', 'autumn', 'summer', 'winter', 'autumn', 'spring', 'summer']
})

# Verificar que las columnas coincidan
print("Columnas de nuevos datos:", nuevos_datos_dificiles.columns.tolist())
print("Columnas esperadas:", X.columns.tolist())

# Realizar predicciones con ambos modelos
predicciones_rf1 = Rand_for_pipeline.predict(nuevos_datos_dificiles)
predicciones_dt1 = dtree_for_pipeline.predict(nuevos_datos_dificiles)
predicciones_lg1 = Log_reg_pipeline.predict(nuevos_datos_dificiles)

print("\n" + "="*50)
print("Predicciones con datos más dificiles")
print("="*50)
print("\nRandom Forest:")
print(predicciones_rf1)
print("\nDecision Tree:")
print(predicciones_dt1)
print("\nRegresion Logistica:")
print(predicciones_lg1)

# Probabilidades de predicción
probabilidades_rf1 = Rand_for_pipeline.predict_proba(nuevos_datos_dificiles)
probabilidades_dt1 = dtree_for_pipeline.predict_proba(nuevos_datos_dificiles)
probabilidades_lg1 = Log_reg_pipeline.predict_proba(nuevos_datos_dificiles)

print("\nProbabilidades - Random Forest:")
print(probabilidades_rf1)
print("\nProbabilidades - Decision Tree:")
print(probabilidades_dt1)
print("\nProbabilidades - Regresion Logistica:")
print(probabilidades_lg1)

"""El estudio realizado permitió identificar al modelo Random Forest como el más confiable para distinguir entre hongos comestibles y venenosos, gracias a su altísima precisión del 99.68% y su capacidad para medir correctamente la incertidumbre en casos dudosos. A diferencia de este, el Árbol de Decisión mostró una confianza exagerada al predecir siempre con 100% de seguridad, lo que indica que memorizó los datos en lugar de aprender patrones generalizables.

Los resultados llevan a descartar la Regresión Logística, cuyo 73.28% de acierto resulta insuficiente para un contexto donde los errores pueden tener consecuencias graves. Aunque el Árbol de Decisión alcanzó 98.57% de precisión, su tendencia al sobreajuste lo hace menos fiable que el Random Forest, que se consolida como la opción ideal para implementar en sistemas prácticos de identificación de hongos.

La implementación del Random Forest en aplicaciones reales representaría un avance concreto en seguridad alimentaria, previniendo intoxicaciones mediante una herramienta accesible y confiable. Este trabajo demuestra cómo el aprendizaje automático puede complementar el conocimiento tradicional, ofreciendo soluciones tecnológicas que mejoran la precisión en la identificación de especies peligrosas.

# <FONT SIZE=5 COLOR="DarkTurquoise"> **2. Regresión** </FONT>

##<FONT SIZE=5 COLOR="purple"> **Análisis de datos** </FONT>
"""

url2= "https://raw.githubusercontent.com/william2208/probabilidad/refs/heads/main/abalone.data"

column_names = [
    "Sex", "Length", "Diameter", "Height",
    "WholeWeight", "ShuckedWeight", "VisceraWeight", "ShellWeight", "Rings"
]

# Cargar el dataset
abalone = pd.read_csv(url2, header=None, names=column_names)

# Cambiar tipos de datos
abalone = abalone.astype({
    "Sex": "category",         # Variable categórica
    "Length": "float",
    "Diameter": "float",
    "Height": "float",
    "WholeWeight": "float",
    "ShuckedWeight": "float",
    "VisceraWeight": "float",
    "ShellWeight": "float",
    "Rings": "int"
})

abalone.columns

abalone.shape

abalone.head()

abalone.info()

abalone.describe()

msno.matrix(abalone)
plt.text(1,210,'no se observan datos atipicos', fontsize=20)
plt.show()

abalone.isna().sum()

"""Podemoss afirmar que por el momento lo mas apropiado es no trabajar con la variablee holidays debido a la gran cantidad de datos nulos que tiene."""

#creamos funciones para analizar las variables mas rapido
def histograma(datos,variable,color,analisis):
  plt.figure(figsize=(10,10))
  sns.histplot(data=datos, x=variable, bins=15, multiple="stack",color=color)
  plt.title(f"Histograma de {variable}")
  plt.text(2,-5,analisis, fontsize=20)
  plt.show()


def boxplot(datos,variable,analisis):
  plt.figure(figsize=(10,10))
  plt.boxplot(datos[variable].dropna())
  plt.title(f"boxplot de {variable}")
  plt.text(2,50,analisis, fontsize=20)
  plt.show()


import numpy as np

def drop_Atip(datos, variable):
    Q1 = np.percentile(datos[variable], 25)
    Q3 = np.percentile(datos[variable], 75)
    IQR = Q3 - Q1

    limite_superior = Q3 + 1.5 * IQR
    limite_inferior = Q1 - 1.5 * IQR

    print("Datos atípicos:")
    print(datos[(datos[variable] < limite_inferior) | (datos[variable] > limite_superior)].shape)

    print("Datos sin atípicos:")
    print(datos[(datos[variable] > limite_inferior) & (datos[variable] < limite_superior)].shape)

    c = datos[variable].mode()
    print("Moda:", c[0])

    b = input('Continuamos reemplazando los atípicos por la moda? s/n: ')
    if b.lower() == "s":
        datos.loc[(datos[variable] < limite_inferior) | (datos[variable] > limite_superior), variable] = c[0]
    else:
        print("Ok, no se realizaron cambios")

histograma(abalone,"Length","Darkred","\nDistribución: La variable parece tener una distribución unimodal (un solo pico) y está ligeramente sesgada a la derecha (la cola se extiende un poco hacia valores mayores). \nRango de datos: Los valores van aproximadamente de 0.1 a 0.8.\nConcentración de datos: La mayoría de los valores se concentran entre 0.4 y 0.65, indicando que la mayor parte de la población se encuentra en este rango.\nPosibles outliers: Hay muy pocos datos en los extremos (cerca de 0.1 y 0.8), podrían considerarse atípicos o simplemente valores poco frecuentes.")

boxplot(abalone,"Length","")

"""Remplazamos datos atipicos"""

drop_Atip(abalone,"Length")

boxplot(abalone,"Length","")

histograma(abalone,"Diameter","Darkorange","")

boxplot(abalone,"Diameter","")

drop_Atip(abalone,"Diameter")

boxplot(abalone,"Diameter","")

histograma(abalone,"Height","Darkgreen","Podemos ver que la distribucion esta ago rara entonces miraremos datos atipicos")

boxplot(abalone,"Height","")

drop_Atip(abalone,"Height")

histograma(abalone,"Height","Darkgreen","")

histograma(abalone,"WholeWeight","Darkblue","")

boxplot(abalone,"WholeWeight","")

drop_Atip(abalone,"WholeWeight")

boxplot(abalone,"WholeWeight","")

histograma(abalone,"ShuckedWeight","Darkviolet","")

boxplot(abalone,"ShuckedWeight","")

drop_Atip(abalone,"ShuckedWeight")

boxplot(abalone,"ShuckedWeight","")

histograma(abalone,"VisceraWeight","Darkred","")

boxplot(abalone,"VisceraWeight","")

drop_Atip(abalone,"VisceraWeight")

boxplot(abalone,"VisceraWeight","")

histograma(abalone,"ShellWeight","Lightgreen","")

boxplot(abalone,"ShellWeight","")

drop_Atip(abalone,"ShellWeight")

boxplot(abalone,"ShellWeight","")

histograma(abalone,"Rings","Darkblue","")

boxplot(abalone,"Rings","")

drop_Atip(abalone,"Rings")

boxplot(abalone,"Rings","")

sns.countplot(x='Sex',data=abalone,palette='Set3')
plt.title("Genero")
plt.show()

plt.figure(figsize=(10,10))
desfase=[0.15,0.15,0.15]
colores=["#02B3DB","#7012DE","#9810FA","#42D3F2","#721378","#A50C36","#AD46FF"]
abalone['Sex'].value_counts().plot.pie(labels=[""]*len(abalone["Sex"].unique()),autopct="%1.1f%%", startangle=90,colors=colores, explode=desfase, textprops={'fontsize': 10})
plt.ylabel("")
plt.legend(abalone['Sex'].unique(), title="genero", loc="center left", bbox_to_anchor=(1, 0.5))
plt.show()

matriz=abalone.drop("Sex",axis=1,inplace=False).corr()
plt.figure(figsize=(10,10))
sns.heatmap(matriz,annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title("Matriz de correlación")
plt.text(0.5,7, '', fontsize=12)
plt.show()

"""<FONT SIZE=5 COLOR="purple"> **Análisis** </FONT>

Length (Longitud): La distribución es unimodal y ligeramente sesgada a la derecha, con valores que oscilan aproximadamente entre 0.1 y 0.8. La mayoría de los datos se concentran entre 0.4 y 0.65. Antes de la eliminación de valores atípicos, el diagrama de caja mostraba numerosos outliers en ambos extremos, especialmente en valores bajos. Después de la eliminación, el rango se redujo, indicando mayor concentración de datos y menor variabilidad.

Diameter (Diámetro): La distribución es unimodal y ligeramente sesgada a la derecha, con un rango aproximado de 0.1 a 0.6, y la mayoría de los valores entre 0.35 y 0.5. Los outliers eran notorios, especialmente en valores bajos. Tras la eliminación, el diagrama de caja se volvió más compacto con outliers drásticamente reducidos.

Height (Altura): El diagrama de caja inicial reveló numerosos outliers, incluidos valores cercanos a cero, lo que sugiere posibles errores de medición. Después de la eliminación de outliers, el histograma mostró una distribución más normalizada y concentrada.

WholeWeight (Peso Total): Esta variable muestra una distribución sesgada a la derecha, con la mayoría de los abalones concentrados en pesos entre 0.25 y 1.0 (rango 0 a 2.5). El diagrama de caja inicial mostró outliers significativos en el extremo superior. La eliminación de outliers resultó en un rango más estrecho y menos valores atípicos, proporcionando una distribución central más clara.

ShuckedWeight (Peso Descartado): Similar a WholeWeight, su distribución está sesgada a la derecha, con valores mayormente entre 0.1 y 0.5 (rango 0 a 1.2). El diagrama de caja inicialmente presentaba claros outliers en el extremo superior. Después de la eliminación, el diagrama mostró un rango más conciso y menor dispersión.

VisceraWeight (Peso de Vísceras): Esta variable también presenta una distribución sesgada a la derecha, con la mayoría de los datos entre 0.05 y 0.25 (rango 0 a 0.7). El diagrama de caja antes del tratamiento mostró outliers considerables en el extremo superior. Tras la eliminación, la distribución se volvió más compacta y representativa.

ShellWeight (Peso de Concha): La distribución está sesgada a la derecha, con un pico en valores bajos a medios (rango 0 a 0.9), y la mayoría de los datos concentrados entre 0.1 y 0.4. El diagrama de caja inicial presentaba outliers en la parte superior. Tras la eliminación de outliers, el diagrama quedó más ajustado con menos valores atípicos.

Rings (Anillos): La distribución es aproximadamente unimodal, ligeramente sesgada a la derecha, con un rango de 1 a 29 anillos, y la mayoría de los abalones tienen entre 8 y 12 anillos. El diagrama de caja antes del tratamiento mostraba un número considerable de outliers en el extremo superior, lo que sugiere abalones inusualmente viejos. Tras la eliminación de outliers, el diagrama se volvió más centrado y menos disperso, proporcionando una representación más robusta de la edad típica.

Sex (Sexo): El gráfico de conteo de 'Sex' indica que las categorías 'M' (masculino) e 'I' (infante) son las más frecuentes, seguidas de 'F' (femenino).
"""

# variable objetivo
z=abalone.drop("Sex",axis=1)
y =z['Rings']
# variables predictoras
X =z.drop('Rings', axis=1)

# conjunto de entrenamiento y prueba
X_train,X_test,y_train,y_test=train_test_split(X,
                                               y,
                                               train_size=0.70,
                                               random_state=123)

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

"""##<FONT SIZE=5 COLOR="purple"> **KNN** </FONT>"""

from sklearn.neighbors import KNeighborsRegressor
KNN=KNeighborsRegressor(n_neighbors=5)
KNN.fit(X_train_s, y_train)
y_pred = KNN.predict(X_test_s)

print("R2",r2_score(y_test, y_pred))                             # coeficiente de determinación
print('MSE', mean_squared_error(y_test, y_pred))                 # error cuadrático medio
print('RMSE', np.sqrt(mean_squared_error(y_test,y_pred)))        # raíz error cuadrático medio

evaluacion_regresion(KNN, X_train_s, y_train, X_test_s, y_test)

comparacion = pd.DataFrame({
    "Real": y_test[:10],
    "Predicho": y_pred[:10]
})

comparacion

nuevo=[[0.5,0.262,0.09,0.5140,0.152,0.01415,0.055]]
nuevo_s = scaler.transform(nuevo)
prediccion = KNN.predict(nuevo_s)

print("Predicción:", prediccion)

nuevo2=[[0.4,0.362,0.1,0.5140,0.252,0.02415,0.055]]
nuevo_s2= scaler.transform(nuevo2)
prediccion = KNN.predict(nuevo_s2)

print("Predicción:", prediccion)

"""##<FONT SIZE=5 COLOR="purple"> **Regresión multiple** </FONT>"""

# modelo de regresión lineal
modelo = LinearRegression()
# entrenamiento
modelo.fit(X_train_s,y_train)
# predicción
y_pred = modelo.predict(X_test_s)
# evaluación del modelo
print("R2",r2_score(y_test, y_pred))                             # coeficiente de determinación
print('MSE', mean_squared_error(y_test, y_pred))                 # error cuadrático medio
print('RMSE', np.sqrt(mean_squared_error(y_test,y_pred)))        # raíz error cuadrático medio

modelo.predict(nuevo_s)

modelo.predict(nuevo_s2)

comparacion = pd.DataFrame({
    "Real": y_test[:10],
    "Predicho": y_pred[:10]
})

comparacion

evaluacion_regresion(modelo, X_train_s, y_train, X_test_s, y_test)

nuevo=[[]]

"""##<FONT SIZE=5 COLOR="purple"> **SVR** </FONT>"""

model_svr = SVR(kernel='rbf', C=1.0, epsilon=0.1)
# 2. ENTRENAMIENTO
model_svr.fit(X_train_s, y_train)
# 3. PREDICCIÓN
y_pred_svr = model_svr.predict(X_test_s)
# 4. MÉTRICAS
print("--- Resultados SVR (Support Vector Regression) ---")
print("R2 (Coef. Determinación):", r2_score(y_test, y_pred_svr))
print('MSE (Error Cuadrático Medio):', mean_squared_error(y_test, y_pred_svr))
print('RMSE (Raíz del Error):', np.sqrt(mean_squared_error(y_test, y_pred_svr)))

model_svr.predict(nuevo_s)

model_svr.predict(nuevo_s2)

comparacion = pd.DataFrame({
    "Real": y_test[:10],
    "Predicho": y_pred[:10]
})

comparacion

evaluacion_regresion(model_svr, X_train_s, y_train, X_test_s, y_test)

"""##<FONT SIZE=5 COLOR="purple"> **Cual es mejor?** </FONT>
## Resultados por Modelo:

### **KNN**
- **R²**: Train 0.582 | Test 0.415
- **MSE**: Train 2.198 | Test 3.182
- **MAE**: Train 1.137 | Test 1.394

### **Regresión Múltiple**
- **R²**: Train 0.373 | Test 0.393
- **MSE**: Train 3.299 | Test 3.301
- **MAE**: Train 1.393 | Test 1.402

### **Support Vector**
- **R²**: Train 0.456 | Test 0.454
- **MSE**: Train 2.864 | Test 2.973
- **MAE**: Train 1.250 | Test 1.293

---

## Evaluación por Criterios:

### **Capacidad Predictiva (R² Test)**
1. **Support Vector**: 0.454
2. **KNN**: 0.415
3. **Regresión Múltiple**: 0.393

###  **Error de Predicción (MSE Test)**
1. **Support Vector**: 2.973
2. **KNN**: 3.182
3. **Regresión Múltiple**: 3.301

### **Generalización (Diferencia Train-Test)**
- **Support Vector**: Mínima diferencia
- **Regresión Múltiple**: Pequeña diferencia
- **KNN**: Gran diferencia (sobreajuste)

###  **Consistencia (MAE Test)**
1. **Support Vector**: 1.293
2. **KNN**: 1.394
3. **Regresión Múltiple**: 1.402

---

## **CONCLUSIÓN FINAL**

**MODELO GANADOR: SUPPORT VECTOR**

**Razones principales:**
- Mayor poder predictivo (R² más alto en test)
- Menor error en predicciones (MSE y MAE más bajos)
- Mejor capacidad de generalización
- Más consistente y estable

**Recomendación:** Implementar el modelo de Support Vector para predicciones futuras.

# <FONT SIZE=5 COLOR="DarkTurquoise"> **3. Clustering** </FONT>

##<FONT SIZE=5 COLOR="purple"> **Análisis de datos** </FONT>

Acá va la info de la base de datos
"""

url="https://raw.githubusercontent.com/william2208/machine-learning/refs/heads/main/gt_2011.csv"

gt= pd.read_csv(url)

gt.columns

gt.info()

gt.describe()

msno.matrix(gt)
plt.text(1,210,'', fontsize=20)
plt.show()

print("podemoss ver que no hay datos nulos")

gt.isna().sum()

"""###para AT"""

def histograma(datos,variable,color,analisis):
  plt.figure(figsize=(10,10))
  sns.histplot(data=datos, x=variable, bins=15, multiple="stack",color=color)
  plt.title(f"Histograma de {variable}")
  plt.text(2,-5,analisis, fontsize=20)
  plt.show()

histograma(gt,"AT","Yellow","")

"""Distribución: La variable AT muestra una distribución que se asemeja a una campana, con una ligera asimetría a la izquierda (cola extendida hacia valores más bajos). Rango: La temperatura ambiente varía aproximadamente entre 2 y 35 grados Celsius. Concentración: La mayoría de las observaciones se encuentran entre 10 y 25 grados Celsius."""

boxplot(gt,"AT","")

"""Distribución: El boxplot de AT muestra una distribución simétrica con la mediana cerca del centro. Los bigotes son de longitud similar y no se observan outliers, lo que indica una distribución de datos muy consistente y sin valores extremos.

###Para AP
"""

histograma(gt,"AP","Yellow","")

"""Distribución: La variable AP tiene una distribución compacta y ligeramente asimétrica a la izquierda, con la mayoría de los valores agrupados alrededor de la media. Rango: La presión ambiente se encuentra entre 995 y 1035 mbar. Concentración: La mayor concentración de datos está entre 1010 y 1020 mbar."""

boxplot(gt,"AP","")

"""Distribución: El boxplot de AP presenta una mediana central con una distribución relativamente simétrica. Sin embargo, se observan algunos puntos aislados en los extremos, lo que indica la presencia de pocos outliers en la presión ambiente."""

#trataamos atipicos
drop_Atip(gt,"AP")

histograma(gt,"AP","Yellow","")

"""Efecto de la eliminación de outliers: Tras remover los outliers, el histograma de AP muestra una distribución aùn más concentrada y simétrica, con un rango de valores más estrecho, lo que refuerza la representatividad de la mayoría de los datos."""

boxplot(gt,"AP","")

"""Efecto de la eliminación de outliers: La eliminación de outliers en AP ha resultado en un boxplot sin puntos atípicos, confirmando una distribución más limpia y una mejor representación de los valores centrales de la presión ambiente.

###Para AH
"""

histograma(gt,"AH","Orange","")

"""Distribución: La variable AH exhibe una distribución con un pico principal y una cola que se extiende hacia valores más bajos, indicando una ligera asimetría a la izquierda. Rango: La humedad ambiente varía desde aproximadamente 30% hasta 100%. Concentración: La mayoría de los datos se agrupan entre 70% y 95%."""

boxplot(gt,"AH","")

"""Distribución: El boxplot de AH muestra una distribución relativamente compacta con una mediana cerca del centro. Se observan algunos outliers en el extremo inferior, lo que sugiere episodios de humedad ambiente inusualmente baja."""

drop_Atip(gt,"AH")

histograma(gt,"AH","Orange","")

"""Efecto de la eliminación de outliers: Al remover los outliers, el histograma de AH se vuelve más centrado y simétrico, eliminando la cola inferior y mejorando la visualización de la concentración de datos."""

boxplot(gt,"AH","")

"""Efecto de la eliminación de outliers: El boxplot de AH después de la limpieza muestra una distribución sin outliers, lo que indica una representación más robusta y confiable de la humedad ambiente típica.

###para AFDP
"""

histograma(gt,"AFDP","purple","")

"""Distribución: La variable AFDP presenta una distribución asimétrica a la derecha, con la mayoría de los valores concentrados en el rango inferior y una cola que se extiende hacia valores más altos. Rango: La diferencia de presión del filtro de aire oscila entre aproximadamente 2.7 y 7.3. Concentración: La mayoría de los datos se encuentran entre 3.5 y 4.5."""

boxplot(gt,"AFDP","")

"""Distribución: El boxplot de AFDP muestra una distribución con la mediana hacia el extremo inferior del rango intercuartílico, y una presencia notoria de outliers en el extremo superior. Esto sugiere que hay momentos en que la diferencia de presión del filtro de aire es significativamente más alta de lo usual."""

drop_Atip(gt,"AFDP")

histograma(gt,"AFDP","purple","")

"""Efecto de la eliminación de outliers: El histograma de AFDP, después de la remoción de outliers, muestra una distribución más uniforme y menos sesgada, con una concentración más clara en los valores medios."""

boxplot(gt,"AFDP","")

"""Efecto de la eliminación de outliers: El boxplot de AFDP sin outliers se presenta más simétrico y con un rango de datos más ajustado, lo que indica que los valores extremos fueron correctamente identificados y tratados.

###para GTEP
"""

histograma(gt,"GTEP","turquoise","")

"""Distribución: La variable GTEP muestra una distribución que tiende a ser bimodal o con dos picos, uno alrededor de 23-25 y otro alrededor de 30. Rango: La presión de escape de la turbina de gas varía aproximadamente entre 18 y 36. Concentración: Se observan dos concentraciones principales de datos."""

boxplot(gt,"GTEP","")

"""Distribución: El boxplot de GTEP presenta una distribución con la mediana ubicada en el centro del rango intercuartílico y bigotes de longitud similar. No se detectan outliers, lo que sugiere una operación estable sin presiones de escape extremadamente inusuales.

###Para TIT
"""

histograma(gt,"TIT","Darkred","")

"""Distribución: La variable TIT muestra una distribución asimétrica a la izquierda, con la mayoría de los valores concentrados en el rango superior y una cola que se extiende hacia valores más bajos. Rango: La temperatura de entrada de la turbina varía aproximadamente entre 1000 y 1100. Concentración: La mayoría de los datos se agrupan entre 1080 y 1100."""

boxplot(gt,"TIT","")

"""Distribución: El boxplot de TIT revela una distribución con la mediana hacia el extremo superior del rango intercuartílico, y una cantidad muy elevada de outliers en el extremo inferior. Esto sugiere que la turbina ha operado frecuentemente con temperaturas de entrada significativamente más bajas de lo normal, posiblemente por paradas o arranques."""

drop_Atip(gt,"TIT")

histograma(gt,"TIT","Darkred","")

"""Efecto de la eliminación de outliers: El histograma de TIT, tras la eliminación de outliers, exhibe una distribución mucho más estrecha y concentrada en los valores altos, eliminando la cola inferior y mostrando la operación normal de la turbina."""

boxplot(gt,"TIT","")

"""Efecto de la eliminación de outliers: El boxplot de TIT después de la limpieza de outliers muestra una distribución con un rango intercuartílico muy ajustado y sin puntos atípicos, lo que representa con mayor precisión el régimen operativo típico de la temperatura de entrada de la turbina.

###para TAT
"""

histograma(gt,"TAT","Darkorange","")

"""Distribución: La variable TAT presenta una distribución con dos picos o una ligera bimodalidad, aunque con la mayoría de los valores concentrados en el rango superior. Rango: La temperatura de escape de la turbina varía aproximadamente entre 510 y 550. Concentración: Se observan dos grupos de valores, uno alrededor de 515-525 y otro alrededor de 545-550."""

boxplot(gt,"TAT","")

"""Distribución: El boxplot de TAT muestra una distribución relativamente simétrica con la mediana cerca del centro. Se observa la presencia de algunos outliers en el extremo inferior, lo que indica episodios aislados de temperaturas de escape inusualmente bajas."""

drop_Atip(gt,"TAT")

boxplot(gt,"TAT","")

"""Efecto de la eliminación de outliers: El boxplot de TAT después de la limpieza muestra una distribución sin outliers, lo que refleja una operación más estable y un rango de temperaturas de escape más predecible."""

histograma(gt,"TAT","Darkorange","")

"""Efecto de la eliminación de outliers: El histograma de TAT, después de la eliminación de outliers, presenta una distribución más enfocada en los valores más frecuentes, con una reducción en la dispersión y una forma más clara de los picos principales.

###para TEY
"""

histograma(gt,"TEY","Darkgreen","")

"""Distribución: La variable TEY exhibe una distribución bimodal clara, con dos picos pronunciados. Rango: El rendimiento energético de la turbina varía desde aproximadamente 100 hasta 170. Concentración: Se observan dos grupos principales de valores, uno alrededor de 125-135 y otro alrededor de 145-155."""

boxplot(gt,"TEY","")

"""Distribución: El boxplot de TEY muestra una distribución con una mediana central. Se identifican algunos outliers en ambos extremos, lo que sugiere variaciones inusuales en el rendimiento energético de la turbina, tanto por debajo como por encima de lo normal."""

drop_Atip(gt,"TEY")

boxplot(gt,"TEY","")

"""Efecto de la eliminación de outliers: El boxplot de TEY sin outliers presenta una distribución más limpia y sin puntos atípicos, lo que facilita la interpretación de los dos modos operativos principales de la turbina."""

histograma(gt,"TEY","Darkgreen","")

"""Efecto de la eliminación de outliers: El histograma de TEY, tras la eliminación de outliers, mantiene su bimodalidad pero con una definición más nítida de los dos picos y una reducción de la dispersión en los extremos.

###para CDP
"""

histograma(gt,"CDP","Darkblue","")

"""Distribución: La variable CDP muestra una distribución que se asemeja a una campana, con una ligera asimetría a la izquierda (cola extendida hacia valores más bajos). Rango: La presión de descarga del compresor varía aproximadamente entre 9.9 y 14.8. Concentración: La mayoría de las observaciones se encuentran entre 11 y 13.5."""

boxplot(gt,"CDP","")

"""Distribución: El boxplot de CDP muestra una distribución simétrica con la mediana cerca del centro. Los bigotes son de longitud similar y no se observan outliers, lo que indica una distribución de datos muy consistente y sin valores extremos en la presión de descarga del compresor.

###para CO
"""

histograma(gt,"CO","Darkviolet","")

"""Distribución: La variable CO presenta una distribución fuertemente asimétrica a la derecha, con una alta concentración de valores bajos y una cola muy larga que se extiende hacia valores altos. Rango: El monóxido de carbono varía desde valores muy cercanos a cero hasta aproximadamente 43. Concentración: La inmensa mayoría de los datos se agrupan en valores muy bajos, indicando una baja emisión de CO en condiciones normales."""

boxplot(gt,"CO","")

"""Distribución: El boxplot de CO exhibe una mediana muy baja y un rango intercuartílico estrecho, pero una cantidad masiva de outliers en el extremo superior. Esto indica que, aunque la emisión de CO es generalmente baja, hay picos significativos y frecuentes de emisiones elevadas."""

drop_Atip(gt,"CO")

histograma(gt,"CO","Darkviolet","")

"""Efecto de la eliminación de outliers: El histograma de CO, después de la limpieza de outliers, muestra una distribución mucho más compacta y enfocada en los valores bajos, resaltando que la emisión de CO es normalmente reducida, y los picos anteriores eran eventos atípicos."""

boxplot(gt,"CO","")

"""Efecto de la eliminación de outliers: El boxplot de CO sin outliers es mucho más representativo de las emisiones típicas, con un rango intercuartílico y bigotes muy cortos, indicando una variabilidad muy baja en condiciones normales.

###para NOX
"""

histograma(gt,"NOX","Lightgreen","")

"""Distribución: La variable NOX muestra una distribución con una forma que se asemeja a una campana, aunque con una ligera asimetría a la derecha. Rango: Los óxidos de nitrógeno varían aproximadamente entre 27 y 119. Concentración: La mayoría de los valores se concentran entre 55 y 80."""

boxplot(gt,"NOX","")

"""Distribución: El boxplot de NOX presenta una distribución relativamente simétrica con la mediana cerca del centro. Se observan outliers en el extremo superior, lo que sugiere algunos picos de emisiones de óxidos de nitrógeno inusualmente altos."""

drop_Atip(gt,"NOX")

histograma(gt,"NOX","Lightgreen","")

"""Efecto de la eliminación de outliers: El histograma de NOX, después de la remoción de outliers, muestra una distribución más simétrica y centrada, con una reducción en la cola derecha, lo que mejora la representación de las emisiones típicas."""

boxplot(gt,"NOX","")

"""Efecto de la eliminación de outliers: El boxplot de NOX sin outliers se presenta más limpio y con un rango de variabilidad más ajustado, lo que indica que los valores extremos fueron correctamente identificados y tratados, y que las emisiones son más estables en condiciones normales.

## <FONT SIZE=5 COLOR="purple"> **Resumen del Análisis de Datos de Clustering** </FONT>

Después de realizar un análisis exhaustivo de cada variable en el dataset de la turbina de gas (GT_2011), se obtuvieron las siguientes conclusiones:

*   **AT (Temperatura Ambiente):** La distribución es similar a una campana, ligeramente asimétrica a la izquierda, con la mayoría de las observaciones entre 10 y 25 grados Celsius. El boxplot confirma una distribución simétrica sin outliers, indicando una consistencia en los datos.

*   **AP (Presión Ambiente):** Muestra una distribución compacta y ligeramente asimétrica a la izquierda, concentrada entre 1010 y 1020 mbar. Aunque se identificaron y trataron algunos outliers en los extremos, la distribución principal es robusta.

*   **AH (Humedad Ambiente):** Presenta un pico principal y una cola hacia valores más bajos, con la mayoría de los datos agrupados entre 70% y 95%. La eliminación de outliers en el extremo inferior resultó en una distribución más centrada y simétrica.

*   **AFDP (Diferencia de Presión del Filtro de Aire):** Exhibe una distribución asimétrica a la derecha, con valores concentrados entre 3.5 y 4.5. Los outliers significativos en el extremo superior fueron tratados, lo que llevó a una distribución más uniforme y menos sesgada.

*   **GTEP (Presión de Escape de la Turbina de Gas):** Muestra una distribución que tiende a ser bimodal, con dos picos alrededor de 23-25 y 30. El boxplot no detecta outliers, sugiriendo una operación estable sin presiones de escape inusualmente extremas.

*   **TIT (Temperatura de Entrada de la Turbina):** La distribución es asimétrica a la izquierda, con la mayoría de los valores concentrados entre 1080 y 1100. Se encontró una elevada cantidad de outliers en el extremo inferior, cuyo tratamiento resultó en una distribución más estrecha y concentrada, reflejando el régimen operativo normal de la turbina.

*   **TAT (Temperatura de Escape de la Turbina):** Presenta una distribución con dos picos o una ligera bimodalidad, concentrada en el rango superior. Los outliers en el extremo inferior fueron tratados, lo que condujo a una distribución más estable y predecible.

*   **TEY (Rendimiento Energético de la Turbina):** Muestra una clara distribución bimodal con dos picos pronunciados. Después de tratar algunos outliers en ambos extremos, la bimodalidad se mantuvo más nítida, lo que sugiere la existencia de dos modos operativos principales de la turbina.

*   **CDP (Presión de Descarga del Compresor):** La distribución es similar a una campana, ligeramente asimétrica a la izquierda, con la mayoría de las observaciones entre 11 y 13.5. No se observaron outliers, indicando una alta consistencia.

*   **CO (Monóxido de Carbono):** Presenta una distribución fuertemente asimétrica a la derecha, con una alta concentración de valores bajos. Se encontró una cantidad masiva de outliers en el extremo superior. El tratamiento de estos outliers reveló que las emisiones de CO son normalmente reducidas, siendo los picos eventos atípicos.

*   **NOX (Óxidos de Nitrógeno):** Muestra una distribución similar a una campana, aunque con una ligera asimetría a la derecha, concentrada entre 55 y 80. Los outliers en el extremo superior fueron tratados, lo que resultó en una distribución más simétrica y centrada, reflejando emisiones típicas más estables.

En resumen, el análisis de datos de clustering ha permitido identificar las características principales de cada variable, sus distribuciones y la presencia de valores atípicos. El tratamiento de estos outliers fue crucial para obtener una representación más precisa de los datos y prepararlos adecuadamente para el proceso de clustering, revelando patrones y posibles regímenes operativos en la turbina de gas.

##<FONT SIZE=5 COLOR="purple"> **K-means** </FONT>
"""

#escalamoss loss datos
# Escalamos los datos
scaler = StandardScaler()
scaler.fit(gt)
gtscal= pd.DataFrame(scaler.transform(gt),
                  columns = gt.columns,
                  index = gt.index)
gtscal.head(6)

n = 2
kmeans = KMeans(n_clusters=n,                  #Número de clusters
                random_state=0)                #Semilla aleatoria.
kmeans.fit(gtscal)

# Inertia y centroides
print(kmeans.inertia_)
print(kmeans.cluster_centers_)

# Los datos anteriores pero en DataFrame
centroides = pd.DataFrame(kmeans.cluster_centers_, columns = gtscal.columns)
centroides

# Atributos.
print(kmeans.labels_)

df_cluster = gt.copy()
df_cluster["cluster"] = kmeans.labels_
df_cluster.head()

df_cluster.groupby(by = ["cluster"]).mean()

temp = pd.DataFrame(kmeans.transform(gtscal),)
temp["cluster"] = kmeans.predict(gtscal)
temp["cluster"] = temp["cluster"].astype("category")
sns.scatterplot(data = temp,
                x = 0,
                y = 1,
                hue = "cluster")
plt.show()

import pandas as pd
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Supongamos que ya tienes df_cluster y gtscal, y tus clusters
# df_cluster = gt.copy()
# df_cluster['cluster'] = kmeans.labels_
# df_cluster['cluster'] = df_cluster['cluster'].astype(str)

# Lista de variables numéricas
numericas = gt.columns.tolist()

# Crear subplots dinámicos: una fila por variable
fig = make_subplots(rows=1, cols=len(numericas), subplot_titles=numericas)

# Agregar un boxplot por cada variable
for i, var in enumerate(numericas):
    fig_box = px.box(df_cluster, x='cluster', y=var, color='cluster')
    for trace in fig_box.data:
        fig.add_trace(trace, row=1, col=i+1)

# Ajustar layout
fig.update_layout(
    title_text="Boxplots de todas las variables por Cluster",
    height=600,
    width=300*len(numericas),  # Ajusta el ancho según el número de variables
    showlegend=False
)

fig.show()

"""# <FONT SIZE=5 COLOR="DarkTurquoise"> **4. Redes con Tensorflow-Pytorch** </FONT>"""

#variables
numeric_cols = ['cap-diameter','stem-height','stem-width']
categorical_cols = ['cap-shape','cap-color','does-bruise-or-bleed','gill-color',
 'stem-color','has-ring','habitat','season']
variable_objetivo = data2["class"]

X_R = data2[numeric_cols + categorical_cols].copy()

y_R = variable_objetivo

# Vamos a dividir en tres conjuntos: train, validation y test.
X_temp_R, X_test_R, y_temp_R, y_test_R = train_test_split(X_R,
                                                  y_R,
                                                  test_size=0.2,
                                                  stratify=y,
                                                  random_state=42)

# X_temp (80%) lo partimos en 60% train y 20% val
X_train_R, X_val_R, y_train_R, y_val_R = train_test_split(X_temp_R,
                                                  y_temp_R,
                                                  test_size=0.25,
                                                  stratify=y_temp_R,
                                                  random_state=42)

from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder

# Preprocesamiento para redes neuronales
preprocessor_nn = ColumnTransformer([
    ('num', StandardScaler(), numeric_cols),
    ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_cols)
], remainder='drop')

X_train_processed = preprocessor.fit_transform(X_train_R)
X_val_processed = preprocessor.transform(X_val_R)
X_test_processed = preprocessor.transform(X_test_R)

le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train_R)
y_val_encoded = le.transform(y_val_R)
y_test_encoded = le.transform(y_test_R)

print(f"Dimensiones de los conjuntos:")
print(f"Train: {X_train_processed.shape}")
print(f"Validation: {X_val_processed.shape}")
print(f"Test: {X_test_processed.shape}")

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

class MushroomDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32).view(-1, 1)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

# Crear datasets
train_dataset = MushroomDataset(X_train_processed.toarray(), y_train_encoded)
val_dataset = MushroomDataset(X_val_processed.toarray(), y_val_encoded)
test_dataset = MushroomDataset(X_test_processed.toarray(), y_test_encoded)

# Crear dataloaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# Verificar un batch
for batch_X, batch_y in train_loader:
    print(f"Tamaño del batch X: {batch_X.shape}")
    print(f"Tamaño del batch y: {batch_y.shape}")
    break

class MushroomClassifier(nn.Module):
    def __init__(self, input_size):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_size, 64),    # Capa de entrada
            nn.ReLU(),
            nn.Dropout(0.3),

            nn.Linear(64, 32),           # Capa oculta 1
            nn.ReLU(),
            nn.Dropout(0.2),

            nn.Linear(32, 16),           # Capa oculta 2
            nn.ReLU(),
            nn.Dropout(0.1),

            nn.Linear(16, 1)             # Capa de salida
        )

    def forward(self, x):
        return self.net(x)

# Instanciar modelo
input_size = X_train_processed.shape[1]
model = MushroomClassifier(input_size)
print(f"Modelo creado con {input_size} características de entrada")

# Funcion Perdida Y Optimización
criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

def train_model(model, train_loader, val_loader, criterion, optimizer, num_epochs=50):
    train_losses = []
    val_accuracies = []

    for epoch in range(num_epochs):
        # Fase de entrenamiento
        model.train()
        running_loss = 0.0

        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch, y_batch

            # Forward pass
            optimizer.zero_grad()
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)

            # Backward pass
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * X_batch.size(0)

        # Pérdida promedio por época
        epoch_loss = running_loss / len(train_loader.dataset)
        train_losses.append(epoch_loss)

        # Fase de validación
        model.eval()
        all_preds = []
        all_targets = []

        with torch.no_grad():
            for X_batch, y_batch in val_loader:
                X_batch, y_batch = X_batch, y_batch

                outputs = model(X_batch)
                probs = torch.sigmoid(outputs)
                preds = (probs >= 0.5).float()

                all_preds.extend(preds.cpu().numpy())
                all_targets.extend(y_batch.cpu().numpy())

        # Calcular accuracy
        val_acc = accuracy_score(all_targets, all_preds)
        val_accuracies.append(val_acc)

        if (epoch + 1) % 10 == 0:
            print(f'Época [{epoch+1}/{num_epochs}], Pérdida: {epoch_loss:.4f}, Accuracy Validación: {val_acc:.4f}')

    return train_losses, val_accuracies

train_losses, val_accuracies = train_model(
    model, train_loader, val_loader, criterion, optimizer, num_epochs=100
)

# Graficas Del Entrenamiento
plt.figure(figsize=(12, 4))

# Gráfica de pérdida
plt.subplot(1, 2, 1)
plt.plot(train_losses)
plt.title('Pérdida durante el Entrenamiento')
plt.xlabel('Época')
plt.ylabel('Pérdida')
plt.grid(True)

# Gráfica de accuracy
plt.subplot(1, 2, 2)
plt.plot(val_accuracies)
plt.title('Accuracy en Validación')
plt.xlabel('Época')
plt.ylabel('Accuracy')
plt.grid(True)

plt.tight_layout()
plt.show()

def evaluate_model(model, test_loader):
    model.eval()
    all_preds = []
    all_probs = []
    all_targets = []

    with torch.no_grad():
        for X_batch, y_batch in test_loader:
            X_batch, y_batch = X_batch, y_batch

            outputs = model(X_batch)
            probs = torch.sigmoid(outputs)
            preds = (probs >= 0.5).float()

            all_preds.extend(preds.cpu().numpy())
            all_probs.extend(probs.cpu().numpy())
            all_targets.extend(y_batch.cpu().numpy())

    return all_preds, all_probs, all_targets

test_preds, test_probs, test_targets = evaluate_model(model, test_loader)

test_preds_labels = le.inverse_transform(np.array(test_preds).flatten().astype(int))
test_targets_labels = le.inverse_transform(np.array(test_targets).flatten().astype(int))

final_accuracy = accuracy_score(test_targets, test_preds)
print(f"\n")
print("Resuldados Finales")
print(f"\n")
print(f"Accuracy: {final_accuracy:.4f}")

# Matriz de confusión
cm = confusion_matrix(test_targets, test_preds)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Reds',
            xticklabels=le.classes_, yticklabels=le.classes_)
plt.title('Matriz de Confusión - Red Neuronal')
plt.ylabel('Valor Real')
plt.xlabel('Predicción')
plt.show()

# Métricas detalladas
print("\nMétricasS:")
metrics_data = {
    "Métrica": ["Accuracy", "Precision", "Recall", "Specificity", "F1-Score"],
    "Valor": [
        accuracy_score(test_targets, test_preds),
        precision_score(test_targets, test_preds),
        recall_score(test_targets, test_preds),
        specificity_score(test_targets, test_preds),
        f1_score(test_targets, test_preds)
    ]
}
metrics_df = pd.DataFrame(metrics_data)
print(metrics_df.round(4))

# Reporte de clasificación
print("\nReporte de Clasificación:")
print(classification_report(test_targets, test_preds,
                          target_names=le.classes_, digits=4))

"""en conclusión la red neuronal obtuvo un excelente 99.33% de precisión, superando claramente al Árbol de Decisión (98.57%) y a la Regresión Logística (73.28%), aunque no alcanzó el máximo del Random Forest (99.68%). Este resultado la posiciona como la segunda mejor opción, demostrando que los modelos avanzados superan significativamente a los métodos clásicos básicos en la clasificación de hongos.

Al analizar el balance entre clases, la red neuronal mostró un desempeño más equilibrado que el Árbol de Decisión, con solo 43 errores en hongos comestibles y 40 en venenosos. Esta distribución uniforme de aciertos confirma su superioridad sobre modelos clásicos como la Regresión Logística, que presentaba un desbalance notable entre falsos positivos y negativos.

En conclusión, si bien el Random Forest mantiene su ventaja marginal, la red neuronal emerge como una alternativa robusta que supera ampliamente a los modelos clásicos tradicionales. Ambos representan opciones viables para implementación, ofreciendo precisiones superiores al 99% que garantizan confiabilidad en aplicaciones reales de identificación de hongos.

# Bibliografía

Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., & Duchesnay, E. (2011).  
**Scikit-learn: Machine Learning in Python.** *Journal of Machine Learning Research*, 12, 2825–2830.

Waskom, M. L. (2021).  
**Seaborn: Statistical Data Visualization.** *Journal of Open Source Software*, 6(60), 3021.  
https://doi.org/10.21105/joss.03021

University of California, Irvine. (s.f.).  
**Abalone Dataset.** UCI Machine Learning Repository.  
https://archive.ics.uci.edu/dataset/1/abalone

University of California, Irvine. (s.f.).  
**Gas Turbine CO and NOx Emission Dataset.** UCI Machine Learning Repository.  
https://archive.ics.uci.edu/dataset/551/gas+turbine+co+and+nox+emission+data+set

University of California, Irvine. (s.f.).  
**Secondary Mushroom Dataset.** UCI Machine Learning Repository.  
https://archive.ics.uci.edu/dataset/848/secondary+mushroom+dataset
"""